version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "before_install"
          command: |
            echo "before_install"
            sudo apt-get -q update
            sudo apt-get install -qy make apt-transport-https ca-certificates curl software-properties-common gawk jq parallel curl
      - run:
          name: "before_script"
          command: |
            echo "before_script"
            uname -a
            type -a docker-compose && docker-compose version
            docker version
      - run:
          name: "script"
          command: |
            echo "script"
            ( git fetch --unshallow || true ) && git tag -l --sort=creatordate | tail -1
            ci/docker-access.sh
            ci/run-tests.sh

